services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: da_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: host.docker.internal   # points to machine's MySQL
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: LOVEme143
      DB_NAME: personal_cookbook
      JWT_SECRET: fc97985ea1c078ab17d3bd9ff2b49c719d2b3f9eb422c1722fee06123d4d2b066b766cb7f3e13929f8270fa78194e07bee233bcdcce340a7c667bd5c5f4443de
      JWT_EXPIRES_IN: 7d
    extra_hosts:
      - "host.docker.internal:host-gateway"  # needed on Linux
